//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESSI
    {
        public decimal IDACCESSO { get; set; }
        public decimal IDUTENTELOGGATO { get; set; }
        public System.DateTime DATAACCESSO { get; set; }
        public string GUID { get; set; }
    
        public virtual UTENTIAUTORIZZATI UTENTIAUTORIZZATI { get; set; }
    }
}
