//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDC_TRASF
    {
        public decimal ID_CDC_TRASF { get; set; }
        public decimal IDCDC { get; set; }
        public decimal IDTRASFERIMENTO { get; set; }
    
        public virtual CDC CDC { get; set; }
        public virtual TRASFERIMENTO TRASFERIMENTO { get; set; }
    }
}
