//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDENNITA_TFR
    {
        public decimal IDINDENNITA { get; set; }
        public decimal IDTFR { get; set; }
        public System.DateTime DATAOPERAZIONE { get; set; }
    
        public virtual INDENNITA INDENNITA { get; set; }
        public virtual TFR TFR { get; set; }
    }
}
