//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAGFAM_ALTRIDATI
    {
        public decimal IDALTRIDATIFAM { get; set; }
    
        public virtual ALTRIDATIFAM ALTRIDATIFAM { get; set; }
    }
}
