//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATEMAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RATEMAB()
        {
            this.CONTABILITA = new HashSet<CONTABILITA>();
        }
    
        public decimal IDRATEMAB { get; set; }
        public decimal IDMAB { get; set; }
        public System.DateTime DATAINIZIORATA { get; set; }
        public System.DateTime DATAFINERATA { get; set; }
        public decimal GIORNI { get; set; }
        public decimal IMPORTOGIORNO { get; set; }
        public System.DateTime DATAOPERAZIONE { get; set; }
        public decimal ANNULLATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTABILITA> CONTABILITA { get; set; }
        public virtual MAGGIORAZIONEABITAZIONE MAGGIORAZIONEABITAZIONE { get; set; }
    }
}
