//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOCI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOCI()
        {
            this.TEORICI = new HashSet<TEORICI>();
        }
    
        public decimal IDVOCI { get; set; }
        public decimal IDTIPOLIQUIDAZIONE { get; set; }
        public decimal IDTIPOVOCE { get; set; }
        public string CODICEVOCE { get; set; }
        public string DESCRIZIONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEORICI> TEORICI { get; set; }
        public virtual TIPOLIQUIDAZIONE TIPOLIQUIDAZIONE { get; set; }
        public virtual TIPOVOCE TIPOVOCE { get; set; }
    }
}
