//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace NewISE.Areas.Statistiche.RPTDataSet {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DataSet2")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DataSet2 : global::System.Data.DataSet {
        
        private V_OP_EFFETTUATE_CANONE_ANTIDataTable tableV_OP_EFFETTUATE_CANONE_ANTI;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public DataSet2() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected DataSet2(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["V_OP_EFFETTUATE_CANONE_ANTI"] != null)) {
                    base.Tables.Add(new V_OP_EFFETTUATE_CANONE_ANTIDataTable(ds.Tables["V_OP_EFFETTUATE_CANONE_ANTI"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public V_OP_EFFETTUATE_CANONE_ANTIDataTable V_OP_EFFETTUATE_CANONE_ANTI {
            get {
                return this.tableV_OP_EFFETTUATE_CANONE_ANTI;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DataSet2 cln = ((DataSet2)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["V_OP_EFFETTUATE_CANONE_ANTI"] != null)) {
                    base.Tables.Add(new V_OP_EFFETTUATE_CANONE_ANTIDataTable(ds.Tables["V_OP_EFFETTUATE_CANONE_ANTI"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableV_OP_EFFETTUATE_CANONE_ANTI = ((V_OP_EFFETTUATE_CANONE_ANTIDataTable)(base.Tables["V_OP_EFFETTUATE_CANONE_ANTI"]));
            if ((initTable == true)) {
                if ((this.tableV_OP_EFFETTUATE_CANONE_ANTI != null)) {
                    this.tableV_OP_EFFETTUATE_CANONE_ANTI.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DataSet2";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataSet2.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableV_OP_EFFETTUATE_CANONE_ANTI = new V_OP_EFFETTUATE_CANONE_ANTIDataTable();
            base.Tables.Add(this.tableV_OP_EFFETTUATE_CANONE_ANTI);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeV_OP_EFFETTUATE_CANONE_ANTI() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DataSet2 ds = new DataSet2();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void V_OP_EFFETTUATE_CANONE_ANTIRowChangeEventHandler(object sender, V_OP_EFFETTUATE_CANONE_ANTIRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class V_OP_EFFETTUATE_CANONE_ANTIDataTable : global::System.Data.TypedTableBase<V_OP_EFFETTUATE_CANONE_ANTIRow> {
            
            private global::System.Data.DataColumn columnNOMINATIVO;
            
            private global::System.Data.DataColumn columnMATRICOLA;
            
            private global::System.Data.DataColumn columnSEDE;
            
            private global::System.Data.DataColumn columnVALUTA;
            
            private global::System.Data.DataColumn columnDATA_DECORRENZA;
            
            private global::System.Data.DataColumn columnDATA_LETTERA;
            
            private global::System.Data.DataColumn columnDATA_OPERAZIONE;
            
            private global::System.Data.DataColumn columnCAN_CANONE_ANNUO_VALUTA;
            
            private global::System.Data.DataColumn columnCANONE;
            
            private global::System.Data.DataColumn columnQUOTA_MENS;
            
            private global::System.Data.DataColumn columnCAN_PROG_TRASFERIMENTO;
            
            private global::System.Data.DataColumn columnCAN_PROG_CAN_ABITAZIONE;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public V_OP_EFFETTUATE_CANONE_ANTIDataTable() {
                this.TableName = "V_OP_EFFETTUATE_CANONE_ANTI";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal V_OP_EFFETTUATE_CANONE_ANTIDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected V_OP_EFFETTUATE_CANONE_ANTIDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NOMINATIVOColumn {
                get {
                    return this.columnNOMINATIVO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MATRICOLAColumn {
                get {
                    return this.columnMATRICOLA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SEDEColumn {
                get {
                    return this.columnSEDE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn VALUTAColumn {
                get {
                    return this.columnVALUTA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DATA_DECORRENZAColumn {
                get {
                    return this.columnDATA_DECORRENZA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DATA_LETTERAColumn {
                get {
                    return this.columnDATA_LETTERA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DATA_OPERAZIONEColumn {
                get {
                    return this.columnDATA_OPERAZIONE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CAN_CANONE_ANNUO_VALUTAColumn {
                get {
                    return this.columnCAN_CANONE_ANNUO_VALUTA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CANONEColumn {
                get {
                    return this.columnCANONE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QUOTA_MENSColumn {
                get {
                    return this.columnQUOTA_MENS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CAN_PROG_TRASFERIMENTOColumn {
                get {
                    return this.columnCAN_PROG_TRASFERIMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CAN_PROG_CAN_ABITAZIONEColumn {
                get {
                    return this.columnCAN_PROG_CAN_ABITAZIONE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public V_OP_EFFETTUATE_CANONE_ANTIRow this[int index] {
                get {
                    return ((V_OP_EFFETTUATE_CANONE_ANTIRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event V_OP_EFFETTUATE_CANONE_ANTIRowChangeEventHandler V_OP_EFFETTUATE_CANONE_ANTIRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event V_OP_EFFETTUATE_CANONE_ANTIRowChangeEventHandler V_OP_EFFETTUATE_CANONE_ANTIRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event V_OP_EFFETTUATE_CANONE_ANTIRowChangeEventHandler V_OP_EFFETTUATE_CANONE_ANTIRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event V_OP_EFFETTUATE_CANONE_ANTIRowChangeEventHandler V_OP_EFFETTUATE_CANONE_ANTIRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddV_OP_EFFETTUATE_CANONE_ANTIRow(V_OP_EFFETTUATE_CANONE_ANTIRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public V_OP_EFFETTUATE_CANONE_ANTIRow AddV_OP_EFFETTUATE_CANONE_ANTIRow(string NOMINATIVO, short MATRICOLA, string SEDE, string VALUTA, System.DateTime DATA_DECORRENZA, System.DateTime DATA_LETTERA, System.DateTime DATA_OPERAZIONE, double CAN_CANONE_ANNUO_VALUTA, decimal CANONE, decimal QUOTA_MENS, short CAN_PROG_TRASFERIMENTO, short CAN_PROG_CAN_ABITAZIONE) {
                V_OP_EFFETTUATE_CANONE_ANTIRow rowV_OP_EFFETTUATE_CANONE_ANTIRow = ((V_OP_EFFETTUATE_CANONE_ANTIRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        NOMINATIVO,
                        MATRICOLA,
                        SEDE,
                        VALUTA,
                        DATA_DECORRENZA,
                        DATA_LETTERA,
                        DATA_OPERAZIONE,
                        CAN_CANONE_ANNUO_VALUTA,
                        CANONE,
                        QUOTA_MENS,
                        CAN_PROG_TRASFERIMENTO,
                        CAN_PROG_CAN_ABITAZIONE};
                rowV_OP_EFFETTUATE_CANONE_ANTIRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowV_OP_EFFETTUATE_CANONE_ANTIRow);
                return rowV_OP_EFFETTUATE_CANONE_ANTIRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                V_OP_EFFETTUATE_CANONE_ANTIDataTable cln = ((V_OP_EFFETTUATE_CANONE_ANTIDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new V_OP_EFFETTUATE_CANONE_ANTIDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnNOMINATIVO = base.Columns["NOMINATIVO"];
                this.columnMATRICOLA = base.Columns["MATRICOLA"];
                this.columnSEDE = base.Columns["SEDE"];
                this.columnVALUTA = base.Columns["VALUTA"];
                this.columnDATA_DECORRENZA = base.Columns["DATA_DECORRENZA"];
                this.columnDATA_LETTERA = base.Columns["DATA_LETTERA"];
                this.columnDATA_OPERAZIONE = base.Columns["DATA_OPERAZIONE"];
                this.columnCAN_CANONE_ANNUO_VALUTA = base.Columns["CAN_CANONE_ANNUO_VALUTA"];
                this.columnCANONE = base.Columns["CANONE"];
                this.columnQUOTA_MENS = base.Columns["QUOTA_MENS"];
                this.columnCAN_PROG_TRASFERIMENTO = base.Columns["CAN_PROG_TRASFERIMENTO"];
                this.columnCAN_PROG_CAN_ABITAZIONE = base.Columns["CAN_PROG_CAN_ABITAZIONE"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnNOMINATIVO = new global::System.Data.DataColumn("NOMINATIVO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNOMINATIVO);
                this.columnMATRICOLA = new global::System.Data.DataColumn("MATRICOLA", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMATRICOLA);
                this.columnSEDE = new global::System.Data.DataColumn("SEDE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSEDE);
                this.columnVALUTA = new global::System.Data.DataColumn("VALUTA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVALUTA);
                this.columnDATA_DECORRENZA = new global::System.Data.DataColumn("DATA_DECORRENZA", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDATA_DECORRENZA);
                this.columnDATA_LETTERA = new global::System.Data.DataColumn("DATA_LETTERA", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDATA_LETTERA);
                this.columnDATA_OPERAZIONE = new global::System.Data.DataColumn("DATA_OPERAZIONE", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDATA_OPERAZIONE);
                this.columnCAN_CANONE_ANNUO_VALUTA = new global::System.Data.DataColumn("CAN_CANONE_ANNUO_VALUTA", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAN_CANONE_ANNUO_VALUTA);
                this.columnCANONE = new global::System.Data.DataColumn("CANONE", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCANONE);
                this.columnQUOTA_MENS = new global::System.Data.DataColumn("QUOTA_MENS", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQUOTA_MENS);
                this.columnCAN_PROG_TRASFERIMENTO = new global::System.Data.DataColumn("CAN_PROG_TRASFERIMENTO", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAN_PROG_TRASFERIMENTO);
                this.columnCAN_PROG_CAN_ABITAZIONE = new global::System.Data.DataColumn("CAN_PROG_CAN_ABITAZIONE", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCAN_PROG_CAN_ABITAZIONE);
                this.columnNOMINATIVO.MaxLength = 101;
                this.columnMATRICOLA.AllowDBNull = false;
                this.columnSEDE.AllowDBNull = false;
                this.columnSEDE.MaxLength = 35;
                this.columnVALUTA.AllowDBNull = false;
                this.columnVALUTA.MaxLength = 20;
                this.columnDATA_DECORRENZA.AllowDBNull = false;
                this.columnDATA_OPERAZIONE.AllowDBNull = false;
                this.columnCAN_CANONE_ANNUO_VALUTA.AllowDBNull = false;
                this.columnCAN_PROG_TRASFERIMENTO.AllowDBNull = false;
                this.columnCAN_PROG_CAN_ABITAZIONE.AllowDBNull = false;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public V_OP_EFFETTUATE_CANONE_ANTIRow NewV_OP_EFFETTUATE_CANONE_ANTIRow() {
                return ((V_OP_EFFETTUATE_CANONE_ANTIRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new V_OP_EFFETTUATE_CANONE_ANTIRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(V_OP_EFFETTUATE_CANONE_ANTIRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.V_OP_EFFETTUATE_CANONE_ANTIRowChanged != null)) {
                    this.V_OP_EFFETTUATE_CANONE_ANTIRowChanged(this, new V_OP_EFFETTUATE_CANONE_ANTIRowChangeEvent(((V_OP_EFFETTUATE_CANONE_ANTIRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.V_OP_EFFETTUATE_CANONE_ANTIRowChanging != null)) {
                    this.V_OP_EFFETTUATE_CANONE_ANTIRowChanging(this, new V_OP_EFFETTUATE_CANONE_ANTIRowChangeEvent(((V_OP_EFFETTUATE_CANONE_ANTIRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.V_OP_EFFETTUATE_CANONE_ANTIRowDeleted != null)) {
                    this.V_OP_EFFETTUATE_CANONE_ANTIRowDeleted(this, new V_OP_EFFETTUATE_CANONE_ANTIRowChangeEvent(((V_OP_EFFETTUATE_CANONE_ANTIRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.V_OP_EFFETTUATE_CANONE_ANTIRowDeleting != null)) {
                    this.V_OP_EFFETTUATE_CANONE_ANTIRowDeleting(this, new V_OP_EFFETTUATE_CANONE_ANTIRowChangeEvent(((V_OP_EFFETTUATE_CANONE_ANTIRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveV_OP_EFFETTUATE_CANONE_ANTIRow(V_OP_EFFETTUATE_CANONE_ANTIRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSet2 ds = new DataSet2();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "V_OP_EFFETTUATE_CANONE_ANTIDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class V_OP_EFFETTUATE_CANONE_ANTIRow : global::System.Data.DataRow {
            
            private V_OP_EFFETTUATE_CANONE_ANTIDataTable tableV_OP_EFFETTUATE_CANONE_ANTI;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal V_OP_EFFETTUATE_CANONE_ANTIRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableV_OP_EFFETTUATE_CANONE_ANTI = ((V_OP_EFFETTUATE_CANONE_ANTIDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NOMINATIVO {
                get {
                    try {
                        return ((string)(this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.NOMINATIVOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Il valore della colonna \'NOMINATIVO\' nella tabella \'V_OP_EFFETTUATE_CANONE_ANTI\' " +
                                "è DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.NOMINATIVOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short MATRICOLA {
                get {
                    return ((short)(this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.MATRICOLAColumn]));
                }
                set {
                    this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.MATRICOLAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string SEDE {
                get {
                    return ((string)(this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.SEDEColumn]));
                }
                set {
                    this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.SEDEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string VALUTA {
                get {
                    return ((string)(this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.VALUTAColumn]));
                }
                set {
                    this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.VALUTAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime DATA_DECORRENZA {
                get {
                    return ((global::System.DateTime)(this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.DATA_DECORRENZAColumn]));
                }
                set {
                    this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.DATA_DECORRENZAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime DATA_LETTERA {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.DATA_LETTERAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Il valore della colonna \'DATA_LETTERA\' nella tabella \'V_OP_EFFETTUATE_CANONE_ANTI" +
                                "\' è DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.DATA_LETTERAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime DATA_OPERAZIONE {
                get {
                    return ((global::System.DateTime)(this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.DATA_OPERAZIONEColumn]));
                }
                set {
                    this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.DATA_OPERAZIONEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double CAN_CANONE_ANNUO_VALUTA {
                get {
                    return ((double)(this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.CAN_CANONE_ANNUO_VALUTAColumn]));
                }
                set {
                    this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.CAN_CANONE_ANNUO_VALUTAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal CANONE {
                get {
                    try {
                        return ((decimal)(this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.CANONEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Il valore della colonna \'CANONE\' nella tabella \'V_OP_EFFETTUATE_CANONE_ANTI\' è DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.CANONEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal QUOTA_MENS {
                get {
                    try {
                        return ((decimal)(this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.QUOTA_MENSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Il valore della colonna \'QUOTA_MENS\' nella tabella \'V_OP_EFFETTUATE_CANONE_ANTI\' " +
                                "è DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.QUOTA_MENSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short CAN_PROG_TRASFERIMENTO {
                get {
                    return ((short)(this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.CAN_PROG_TRASFERIMENTOColumn]));
                }
                set {
                    this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.CAN_PROG_TRASFERIMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short CAN_PROG_CAN_ABITAZIONE {
                get {
                    return ((short)(this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.CAN_PROG_CAN_ABITAZIONEColumn]));
                }
                set {
                    this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.CAN_PROG_CAN_ABITAZIONEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNOMINATIVONull() {
                return this.IsNull(this.tableV_OP_EFFETTUATE_CANONE_ANTI.NOMINATIVOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNOMINATIVONull() {
                this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.NOMINATIVOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDATA_LETTERANull() {
                return this.IsNull(this.tableV_OP_EFFETTUATE_CANONE_ANTI.DATA_LETTERAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDATA_LETTERANull() {
                this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.DATA_LETTERAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCANONENull() {
                return this.IsNull(this.tableV_OP_EFFETTUATE_CANONE_ANTI.CANONEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCANONENull() {
                this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.CANONEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQUOTA_MENSNull() {
                return this.IsNull(this.tableV_OP_EFFETTUATE_CANONE_ANTI.QUOTA_MENSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQUOTA_MENSNull() {
                this[this.tableV_OP_EFFETTUATE_CANONE_ANTI.QUOTA_MENSColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class V_OP_EFFETTUATE_CANONE_ANTIRowChangeEvent : global::System.EventArgs {
            
            private V_OP_EFFETTUATE_CANONE_ANTIRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public V_OP_EFFETTUATE_CANONE_ANTIRowChangeEvent(V_OP_EFFETTUATE_CANONE_ANTIRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public V_OP_EFFETTUATE_CANONE_ANTIRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591