//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELABINDRICHIAMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ELABINDRICHIAMO()
        {
            this.ELABDATIFIGLI = new HashSet<ELABDATIFIGLI>();
            this.ELABINDRICHIAMO1 = new HashSet<ELABINDRICHIAMO>();
            this.TEORICI = new HashSet<TEORICI>();
        }
    
        public decimal IDELABINDRICHIAMO { get; set; }
        public decimal IDRICHIAMO { get; set; }
        public decimal INDENNITABASE { get; set; }
        public decimal COEFFICENTESEDE { get; set; }
        public decimal COEFFICENTEINDRICHIAMO { get; set; }
        public decimal PERCENTUALERIDUZIONE { get; set; }
        public decimal PERCMAGCONIUGE { get; set; }
        public decimal PENSIONECONIUGE { get; set; }
        public System.DateTime DATAOPERAZIONE { get; set; }
        public bool ANNULLATO { get; set; }
        public Nullable<decimal> FK_IDELABINDRICHIAMO { get; set; }
        public decimal IDLIVELLO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ELABDATIFIGLI> ELABDATIFIGLI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ELABINDRICHIAMO> ELABINDRICHIAMO1 { get; set; }
        public virtual ELABINDRICHIAMO ELABINDRICHIAMO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEORICI> TEORICI { get; set; }
        public virtual LIVELLI LIVELLI { get; set; }
        public virtual RICHIAMO RICHIAMO { get; set; }
    }
}
