//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ALLINEAMENTO
    {
        public decimal IDJOB { get; set; }
        public string JOB { get; set; }
        public string FASE_ELABORAZIONE { get; set; }
        public decimal STATO_ELAB { get; set; }
        public string LOG_ELAB { get; set; }
        public string LOGERROR { get; set; }
        public Nullable<System.DateTime> INIZIO_JOB { get; set; }
        public Nullable<System.DateTime> FINE_JOB { get; set; }
    }
}
