//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGATTIVITA
    {
        public decimal IDLOG { get; set; }
        public decimal IDUTENTELOGGATO { get; set; }
        public Nullable<decimal> IDTRASFERIMENTO { get; set; }
        public decimal IDATTIVITACRUD { get; set; }
        public System.DateTime DATAOPERAZIONE { get; set; }
        public string DESCATTIVITASVOLTA { get; set; }
        public string TABELLACOINVOLTA { get; set; }
        public Nullable<decimal> IDTABELLACOINVOLTA { get; set; }
    
        public virtual ATTIVITACRUD ATTIVITACRUD { get; set; }
        public virtual UTENTIAUTORIZZATI UTENTIAUTORIZZATI { get; set; }
        public virtual TRASFERIMENTO TRASFERIMENTO { get; set; }
    }
}
