//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODIFICHE_MAB
    {
        public decimal IDMODMAB { get; set; }
        public decimal IDATTIVAZIONEMAB { get; set; }
        public decimal IDMSGVAR { get; set; }
        public string VALORE { get; set; }
        public System.DateTime DATAAGGIORNAMENTO { get; set; }
    
        public virtual ATTIVAZIONEMAB ATTIVAZIONEMAB { get; set; }
        public virtual TIPOLOGIAMODIFICHE TIPOLOGIAMODIFICHE { get; set; }
    }
}
