//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGOLECALCOLO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGOLECALCOLO()
        {
            this.RIDUZIONI = new HashSet<RIDUZIONI>();
        }
    
        public decimal IDREGOLA { get; set; }
        public Nullable<decimal> IDTIPOREGOLACALCOLO { get; set; }
        public Nullable<decimal> IDNORMACALCOLO { get; set; }
        public string FORMULAREGOLACALCOLO { get; set; }
        public System.DateTime DATAINIZIOVALIDITA { get; set; }
        public System.DateTime DATAFINEVALIDITA { get; set; }
        public System.DateTime DATAAGGIORNAMENTO { get; set; }
        public bool ANNULLATO { get; set; }
    
        public virtual NORMACALCOLO NORMACALCOLO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIDUZIONI> RIDUZIONI { get; set; }
        public virtual TIPOREGOLACALCOLO TIPOREGOLACALCOLO { get; set; }
    }
}
