//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RINUNCIAANTICIPI
    {
        public decimal IDATTIVITAANTICIPI { get; set; }
        public bool RINUNCIAANT { get; set; }
        public System.DateTime DATAAGGIORNAMENTO { get; set; }
    
        public virtual ATTIVITAANTICIPI ATTIVITAANTICIPI { get; set; }
    }
}
