//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RINUNCIAMAGGIORAZIONIFAMILIARI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RINUNCIAMAGGIORAZIONIFAMILIARI()
        {
            this.RINUNCIAMAGGIORAZIONIFAMILIARI1 = new HashSet<RINUNCIAMAGGIORAZIONIFAMILIARI>();
            this.ATTIVAZIONIMAGFAM = new HashSet<ATTIVAZIONIMAGFAM>();
        }
    
        public decimal IDRINUNCIAMAGFAM { get; set; }
        public decimal IDMAGGIORAZIONIFAMILIARI { get; set; }
        public bool RINUNCIAMAGGIORAZIONI { get; set; }
        public Nullable<System.DateTime> DATAINI { get; set; }
        public Nullable<System.DateTime> DATAFINE { get; set; }
        public System.DateTime DATAAGGIORNAMENTO { get; set; }
        public decimal IDSTATORECORD { get; set; }
        public Nullable<decimal> FK_IDRINUNCIAMAGFAM { get; set; }
    
        public virtual MAGGIORAZIONIFAMILIARI MAGGIORAZIONIFAMILIARI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RINUNCIAMAGGIORAZIONIFAMILIARI> RINUNCIAMAGGIORAZIONIFAMILIARI1 { get; set; }
        public virtual RINUNCIAMAGGIORAZIONIFAMILIARI RINUNCIAMAGGIORAZIONIFAMILIARI2 { get; set; }
        public virtual STATORECORD STATORECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTIVAZIONIMAGFAM> ATTIVAZIONIMAGFAM { get; set; }
    }
}
