//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RINUNCIAMAGGIORAZIONIFAMILIARI
    {
        public decimal IDRINUNCIAMAGFAM { get; set; }
        public Nullable<decimal> IDMAGGIORAZIONIFAMILIARI { get; set; }
        public bool RINUNCIAMAGGIORAZIONI { get; set; }
        public Nullable<System.DateTime> DATAINIZIO { get; set; }
        public Nullable<System.DateTime> DATAFINE { get; set; }
        public System.DateTime DATAAGGIORNAMENTO { get; set; }
        public bool ANNULLATO { get; set; }
    
        public virtual MAGGIORAZIONIFAMILIARI MAGGIORAZIONIFAMILIARI { get; set; }
    }
}
