//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RINUNCIAANTICIPI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RINUNCIAANTICIPI()
        {
            this.ATTIVITAANTICIPI = new HashSet<ATTIVITAANTICIPI>();
        }
    
        public decimal IDRINUNCIAANTICIPI { get; set; }
        public decimal IDPRIMASISTEMAZIONE { get; set; }
        public bool RINUNCIAANTICIPI1 { get; set; }
        public System.DateTime DATAAGGIORNAMENTO { get; set; }
        public bool ANNULLATO { get; set; }
    
        public virtual PRIMASITEMAZIONE PRIMASITEMAZIONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTIVITAANTICIPI> ATTIVITAANTICIPI { get; set; }
    }
}
