//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEORICI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEORICI()
        {
            this.NETTO = new HashSet<NETTO>();
        }
    
        public decimal IDTEORICI { get; set; }
        public decimal IDTIPOMOVIMENTO { get; set; }
        public Nullable<decimal> IDINDSISTLORDA { get; set; }
        public Nullable<decimal> IDELABIND { get; set; }
        public Nullable<decimal> IDELABMAB { get; set; }
        public Nullable<decimal> IDELABTRASPEFFETTI { get; set; }
        public byte MESERIFERIMENTO { get; set; }
        public short ANNORIFERIMENTO { get; set; }
        public decimal GIORNI { get; set; }
        public decimal IMPORTO { get; set; }
        public bool ELABORATO { get; set; }
        public System.DateTime DATAOPERAZIONE { get; set; }
        public bool ANNULLATO { get; set; }
    
        public virtual ELABINDENNITA ELABINDENNITA { get; set; }
        public virtual ELABINDSISTEMAZIONE ELABINDSISTEMAZIONE { get; set; }
        public virtual ELABMAB ELABMAB { get; set; }
        public virtual ELABTRASPEFFETTI ELABTRASPEFFETTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NETTO> NETTO { get; set; }
        public virtual TIPOMOVIMENTO TIPOMOVIMENTO { get; set; }
    }
}
