//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_FK
    {
        public decimal IDTERIENTRO { get; set; }
        public decimal IDCFKM { get; set; }
    
        public virtual TERIENTRO TERIENTRO { get; set; }
    }
}
