//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTENTIAUTORIZZATI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UTENTIAUTORIZZATI()
        {
            this.ACCESSI = new HashSet<ACCESSI>();
            this.LOGATTIVITA = new HashSet<LOGATTIVITA>();
        }
    
        public decimal IDDIPENDENTE { get; set; }
        public decimal IDRUOLOUTENTE { get; set; }
        public string UTENTE { get; set; }
        public string PSW { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCESSI> ACCESSI { get; set; }
        public virtual DIPENDENTI DIPENDENTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGATTIVITA> LOGATTIVITA { get; set; }
        public virtual RUOLOACCESSO RUOLOACCESSO { get; set; }
    }
}
