//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewISE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOCI
    {
        public decimal IDVOCI { get; set; }
        public decimal IDTIPOLIQUIDAZIONE { get; set; }
        public decimal IDTIPOVOCE { get; set; }
        public string CODICEVOCE { get; set; }
        public string DESCRIZIONE { get; set; }
    
        public virtual TIPOVOCE TIPOVOCE { get; set; }
    }
}
